lab-after/OrgVacationManager/API/Controllers/RolesController.cs
using System;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web.Mvc;
using API.Models;
using API.Models.Filters;
using API.Models.ViewModels.Roles;
using API.Models.ViewModels.Users;
using Data;
using Data.Entities;

namespace API.Controllers
{
    public class RolesController : Controller
    {
        [HttpGet]
        public ActionResult Index(RolesIndexVM model)
        {
            if (AuthenticationManager.LoggedUser == null)
                return RedirectToAction("Login", "Home");

            model.Pager = model.Pager ?? new PagerVM();
            model.Pager.Page = model.Pager.Page <= 0 ? 1 : model.Pager.Page;
            model.Pager.ItemsPerPage = model.Pager.ItemsPerPage <= 0 ? 10 : model.Pager.ItemsPerPage;

            model.FilterVm = model.FilterVm ?? new RolesFilterVM();

            bool emptyName = string.IsNullOrWhiteSpace(model.FilterVm.Name);

            OvmDbContext context = new OvmDbContext();
            IQueryable<Role> query = context.Roles.Where(r => emptyName || r.Name.Contains(model.FilterVm.Name));

            model.Pager.PagesCount = (int)Math.Ceiling(query.Count() / (double)model.Pager.ItemsPerPage);

            query = query.OrderBy(r => r.Id).Skip((model.Pager.Page - 1) * model.Pager.ItemsPerPage).Take(model.Pager.ItemsPerPage);

            model.Items = query.Select(r => new RolesVM
            {
                Id = r.Id,
                Name = r.Name,
                AssignedUsersCount = r.Users.Count
            }).ToList();

            context.Dispose();

            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            RolesEditVM item;
            OvmDbContext context = new OvmDbContext();

            if (id == null)
            {
                item = new RolesEditVM();
            }
            else
            {
                Role role = context.Roles.Find(id.Value);

                item = new RolesEditVM
                {
                    Id = id.Value,
                    Name = role.Name
                };
            }

            context.Dispose();

            return View(item);
        }

        [HttpPost]
        public ActionResult Edit(RolesEditVM model)
        {
            OvmDbContext context = new OvmDbContext();

            Role role = new Role
            {
                Id = model.Id,
                Name = model.Name
            };

            context.Roles.AddOrUpdate(u => u.Id, role);
            context.SaveChanges();
            context.Dispose();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            OvmDbContext context = new OvmDbContext();
            Role role = context.Roles.Find(id);
            Role unassignedRole = context.Roles.FirstOrDefault(r => r.Name == "Unassigned");

            foreach (User assignedUser in role.Users)
            {
                assignedUser.Role = unassignedRole ?? new Role("Unassigned");
            }

            context.Roles.Remove(role);
            context.SaveChanges();
            context.Dispose();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            OvmDbContext context = new OvmDbContext();
            Role role = context.Roles.Find(id);

            RolesDetailsVM model = new RolesDetailsVM
            {
                Name = role.Name,
                Users = role.Users.Select(u => new UsersVM
                {
                    Id = u.Id,
                    Username = u.Username,
                    FirstName = u.FirstName,
                    LastName = u.LastName,
                }).ToList()
            };

            return View(model);
        }
    }
}

lab-after/OrgVacationManager/API/Controllers/TimeOffsController.cs
using System;
using System.Configuration;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using API.Models;
using API.Models.Filters;
using API.Models.ViewModels.TimeOffs;
using API.Models.ViewModels.TimeOffs.PaidTimeOffs;
using API.Models.ViewModels.TimeOffs.SickTimeOff;
using API.Models.ViewModels.TimeOffs.UnpaidTimeOffs;
using API.Models.ViewModels.Users;
using API.Services;
using Data;
using Data.Entities;
using Data.Entities.TimeOffs;

namespace API.Controllers
{
    public class TimeOffsController : Controller
    {
        [HttpGet]
        public ActionResult Index(TimeOffsIndexVM model)
        {
            User loggedUser = AuthenticationManager.LoggedUser;

            if (loggedUser == null)
                return RedirectToAction("Index", "Home");

            model.PaidTimeOffsPager = model.PaidTimeOffsPager ?? new PagerVM();
            model.UnpaidTimeOffsPager = model.UnpaidTimeOffsPager ?? new PagerVM();
            model.SickTimeOffsPager = model.SickTimeOffsPager ?? new PagerVM();

            model.PaidTimeOffsPager.Page = model.PaidTimeOffsPager.Page <= 0 ? 1 : model.PaidTimeOffsPager.Page;
            model.UnpaidTimeOffsPager.Page = model.UnpaidTimeOffsPager.Page <= 0 ? 1 : model.UnpaidTimeOffsPager.Page;
            model.SickTimeOffsPager.Page = model.SickTimeOffsPager.Page <= 0 ? 1 : model.SickTimeOffsPager.Page;

            model.PaidTimeOffsPager.ItemsPerPage =
                model.PaidTimeOffsPager.ItemsPerPage <= 0 ? 10 : model.PaidTimeOffsPager.ItemsPerPage;
            model.UnpaidTimeOffsPager.ItemsPerPage = model.UnpaidTimeOffsPager.ItemsPerPage <= 0
                ? 10
                : model.UnpaidTimeOffsPager.ItemsPerPage;
            model.SickTimeOffsPager.ItemsPerPage =
                model.SickTimeOffsPager.ItemsPerPage <= 0 ? 10 : model.SickTimeOffsPager.ItemsPerPage;

            model.PaidTimeOffsFilter = model.PaidTimeOffsFilter ?? new TimeOffsFilterVM();
            model.UnpaidTimeOffsFilter = model.UnpaidTimeOffsFilter ?? new TimeOffsFilterVM();
            model.SickTimeOffsFilter = model.SickTimeOffsFilter ?? new TimeOffsFilterVM();

            bool isPaidDateNotSet = model.PaidTimeOffsFilter.CreatedAfter == null;
            bool isUnpaidDateNotSet = model.UnpaidTimeOffsFilter.CreatedAfter == null;
            bool isSickDateNotSet = model.SickTimeOffsFilter.CreatedAfter == null;

            OvmDbContext context = new OvmDbContext();

            IQueryable<PaidTimeOff> paidQuery = context.PaidTimeOffs.Where(p =>
                p.RequestorId == loggedUser.Id &&
                (isPaidDateNotSet || p.CreatedOn >= model.PaidTimeOffsFilter.CreatedAfter));

            IQueryable<UnpaidTimeOff> unpaidQuery = context.UnpaidTimeOffs.Where(p =>
                p.RequestorId == loggedUser.Id &&
                (isUnpaidDateNotSet || p.CreatedOn >= model.UnpaidTimeOffsFilter.CreatedAfter));

            IQueryable<SickTimeOff> sickQuery = context.SickTimeOffs.Where(p =>
                p.RequestorId == loggedUser.Id &&
                (isSickDateNotSet || p.CreatedOn >= model.SickTimeOffsFilter.CreatedAfter));

            model.PaidTimeOffsPager.PagesCount =
                (int)Math.Ceiling(paidQuery.Count() / (double)model.PaidTimeOffsPager.ItemsPerPage);
            model.UnpaidTimeOffsPager.PagesCount =
                (int)Math.Ceiling(unpaidQuery.Count() / (double)model.UnpaidTimeOffsPager.ItemsPerPage);
            model.SickTimeOffsPager.PagesCount =
                (int)Math.Ceiling(sickQuery.Count() / (double)model.SickTimeOffsPager.ItemsPerPage);

            paidQuery = paidQuery.OrderByDescending(to => to.CreatedOn)
                .Skip((model.PaidTimeOffsPager.Page - 1) * model.PaidTimeOffsPager.ItemsPerPage)
                .Take(model.PaidTimeOffsPager.ItemsPerPage);
            unpaidQuery = unpaidQuery.OrderByDescending(to => to.CreatedOn)
                .Skip((model.UnpaidTimeOffsPager.Page - 1) * model.UnpaidTimeOffsPager.ItemsPerPage)
                .Take(model.UnpaidTimeOffsPager.ItemsPerPage);
            sickQuery = sickQuery.OrderByDescending(to => to.CreatedOn)
                .Skip((model.SickTimeOffsPager.Page - 1) * model.SickTimeOffsPager.ItemsPerPage)
                .Take(model.SickTimeOffsPager.ItemsPerPage);

            model.PaidTimeOffs = paidQuery.Select(pto => new PaidTimeOffsVM
            {
                Id = pto.Id,
                CreatedOn = pto.CreatedOn,
                IsApproved = pto.IsApproved,
                Requestor = new UsersPair
                {
                    Id = pto.Requestor.Id,
                    Username = pto.Requestor.Username
                },
                From = pto.From,
                IsHalfDay = pto.IsHalfDay,
                To = pto.To
            }).ToList();

            model.UnpaidTimeOffs = unpaidQuery.Select(pto => new UnpaidTimeOffsVM
            {
                Id = pto.Id,
                CreatedOn = pto.CreatedOn,
                IsApproved = pto.IsApproved,
                Requestor = new UsersPair
                {
                    Id = pto.Requestor.Id,
                    Username = pto.Requestor.Username
                },
                From = pto.From,
                IsHalfDay = pto.IsHalfDay,
                To = pto.To
            }).ToList();

            model.SickTimeOffs = sickQuery.Select(pto => new SickTimeOffsVM
            {
                Id = pto.Id,
                CreatedOn = pto.CreatedOn,
                IsApproved = pto.IsApproved,
                Requestor = new UsersPair
                {
                    Id = pto.Requestor.Id,
                    Username = pto.Requestor.Username
                },
                From = pto.From,
                To = pto.To
            }).ToList();

            return View(model);
        }

        [HttpGet]
        public ActionResult EditPaid(int? id)
        {
            PaidTimeOffsEditVM model = new PaidTimeOffsEditVM();
            ;
            OvmDbContext context = new OvmDbContext();

            if (id != null)
            {
                PaidTimeOff pto = context.PaidTimeOffs.Find(id.Value);
                model.To = pto.To;
                model.From = pto.From;
                model.IsHalfDay = pto.IsHalfDay;
                model.Id = pto.Id;
            }

            context.Dispose();

            return View(model);
        }

        [HttpPost]
        public ActionResult EditPaid(PaidTimeOffsEditVM model)
        {
            OvmDbContext context = new OvmDbContext();

            PaidTimeOff pto = new PaidTimeOff
            {
                Id = model.Id,
                CreatedOn = DateTime.Now,
                RequestorId = AuthenticationManager.LoggedUser.Id,
                From = model.From,
                To = model.To,
                IsHalfDay = model.IsHalfDay
            };

            context.PaidTimeOffs.AddOrUpdate(pt => pt.Id, pto);
            context.SaveChanges();
            context.Dispose();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult DeletePaid(int id)
        {
            OvmDbContext context = new OvmDbContext();
            PaidTimeOff pto = context.PaidTimeOffs.Find(id);
            context.PaidTimeOffs.Remove(pto);
            context.SaveChanges();
            context.Dispose();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditSick(int? id)
        {
            SickTimeOffsEditVM model = new SickTimeOffsEditVM();
            OvmDbContext context = new OvmDbContext();

            if (id != null)
            {
                SickTimeOff pto = context.SickTimeOffs.Find(id.Value);
                model.To = pto.To;
                model.From = pto.From;
                model.Id = pto.Id;
                model.AttachmentPath = pto.AttachmentPath;
            }

            context.Dispose();

            return View(model);
        }

        [HttpPost]
        public ActionResult EditSick(SickTimeOffsEditVM model)
        {
            OvmDbContext context = new OvmDbContext();

            SickTimeOff sto = new SickTimeOff
            {
                Id = model.Id,
                CreatedOn = DateTime.Now,
                RequestorId = AuthenticationManager.LoggedUser.Id,
                From = model.From,
                To = model.To,
                AttachmentPath = model.Attachment == null
                    ? model.AttachmentPath
                    : StorageService.SaveFile(model.Attachment)
            };

            context.SickTimeOffs.AddOrUpdate(pt => pt.Id, sto);
            context.SaveChanges();
            context.Dispose();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult DeleteSick(int id)
        {
            OvmDbContext context = new OvmDbContext();
            SickTimeOff sto = context.SickTimeOffs.Find(id);
            StorageService.DeleteFile(sto.AttachmentPath);
            context.SickTimeOffs.Remove(sto);
            context.SaveChanges();
            context.Dispose();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult DetailsSick(int id)
        {
            OvmDbContext context = new OvmDbContext();
            SickTimeOff sto = context.SickTimeOffs.Find(id);

            SickTimeOffsDetailsVM model = new SickTimeOffsDetailsVM
            {
                Id = sto.Id,
                From = sto.From,
                To = sto.To,
                IsApproved = sto.IsApproved,
                LastChangedOn = sto.CreatedOn,
            };

            context.Dispose();

            return View(model);
        }

        [HttpGet]
        public ActionResult DownloadAttachment(int id)
        {
            OvmDbContext context = new OvmDbContext();
            SickTimeOff sto = context.SickTimeOffs.Find(id);

lab-after/OrgVacationManager/API/Views/Shared/_Template.cshtml
@{
    var loggedUser = API.Models.AuthenticationManager.LoggedUser;
}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title</title>

    <!-- Custom fonts for this template-->
    @Styles.Render("~/Content/vendor/fontawesome-free/css/all.min.css")
    @Styles.Render(@"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i")

    <!-- Custom styles for this template-->
    @Styles.Render("~/Content/css/sb-admin-2.min.css")

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index", "Home")">
                <div class="sidebar-brand-text mx-3">Org. Vacation Manager</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index", "Home")">
                    <span>Home</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            @if (loggedUser != null)
            {
                <!-- Heading -->
                <div class="sidebar-heading">
                    Administration
                </div>

                <!-- Nav Item - Pages Collapse Menu -->
                <li class="nav-item">
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                        <span>Org. Management</span>
                    </a>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <a class="collapse-item" href="@Url.Action("Index", "Users")">Users</a>
                            <a class="collapse-item" href="@Url.Action("Index", "Teams")">Teams</a>
                            <a class="collapse-item" href="@Url.Action("Index", "Projects")">Projects</a>
                            <a class="collapse-item" href="@Url.Action("Index", "Roles")">Roles</a>
                        </div>
                    </div>
                </li>

                <!-- Divider -->
                <hr class="sidebar-divider">

                <!-- Heading -->
                <div class="sidebar-heading">
                    Requests
                </div>

                <!-- Nav Item - Charts -->
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "TimeOffs")">
                        <span>My requests</span>
                    </a>
                </li>

                if (loggedUser.Role.Name == "CEO" || loggedUser.Role.Name == "Team Lead")
                {
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("AllRequests", "TimeOffs")">
                            <span>All requests</span>
                        </a>
                    </li>
                }

                <!-- Divider -->
                <hr class="sidebar-divider d-none d-md-block">

                <!-- Heading -->
                <div class="sidebar-heading">
                    Authorization
                </div>

                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Logout", "Home")">
                        <span>Logout</span>
                    </a>
                </li>
            }
            else
            {
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Login", "Home")">
                        <span>Login</span>
                    </a>
                </li>
            }

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @if (loggedUser != null)
                                {
                                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">@loggedUser.Username (@loggedUser.Role.Name)</span>
                                }
                            </a>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                @RenderBody()

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Ulpia Tech 2019</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    @Scripts.Render("~/Content/vendor/jquery/jquery.min.js")
    @Scripts.Render("~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js")


    <!-- Core plugin JavaScript-->
    @Scripts.Render("~/Content/vendor/jquery-easing/jquery.easing.min.js")

    <!-- Custom scripts for all pages-->
    @Scripts.Render("~/Scripts/sb-admin-2.min.js")
</body>

</html>